# Generated by Django 4.2.4 on 2023-09-12 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=30)),
                ('descript_producto', models.CharField(max_length=120)),
                ('img_producto', models.ImageField(upload_to='')),
                ('valor_compra', models.IntegerField()),
                ('valor_venta', models.IntegerField()),
                ('activo', models.BooleanField()),
                ('encargado', models.CharField(max_length=30)),
            ],
        ),
    ]
