# Generated by Django 4.2.4 on 2023-09-15 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AirDc', '0007_rename_productos_producto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='valor_venta',
            new_name='precio_producto',
        ),
    ]
