# Generated by Django 4.2.6 on 2024-09-17 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AirDc', '0009_remove_producto_encargado_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='total',
            field=models.FloatField(),
        ),
    ]
